feat: Add paragraphs query options
deepgram-devs/deepgram-rust-sdk pull request #65
Opened 2024-06-03 18:50 UTC by BadMask121

## Proposed changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update or tests (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) doc
- [ ] I have added tests and/or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2024-07-03 15:15 UTC, jcdyer commented
Hi @BadMask121!  Thanks for your contribution.  I'll add some docs to these methods, and get them out the door in our 0.5 release.

2024-07-03 16:14 UTC, jcdyer requested changes
Oops. Spoke too soon. Some tests are failing. See below.

2024-07-03 16:14 UTC, jcdyer commented on src/transcription/prerecorded/options.rs
> +    paragraphs: Option<bool>,
Can you change `filler_words` and `smart_format` to `Option<bool>`, so they don't get serialized unless the user requests them?

2024-07-24 19:55 UTC, DamienDeepgram commented
This has been addressed in this PR: https://github.com/deepgram-devs/deepgram-rust-sdk/pull/76

2024-07-24 19:55 UTC, closed without merging